### ISSUE TITLE
Update Sphinx docs for the latest version of PSLab PCB pin layout

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/pslab-python#100]
The docs are outdated with the names having a mismatch with the current PCB layout of PSLab.
A lack of examples in the doc also makes the use of this library hard.

**Comment by bhadreshpsavani** [comment]
Hey @AakashMallik Where can we find this doc having PCB layout of PSLab

**Comment by Dhriti-Roy** [comment]
@AakashMallik  May I work on this

**Comment by MohitPatni0731** [comment]
Can I work on this

**Comment by Radhika14soni** [comment]
Hey, I'm a first time contributor and I would like to work on this. Any guidance would be appreciated. Thanks!

**Comment by Atri22** [comment]
I am a first time contributor may I work on this. Any guidance will be appreciated

**Comment by prajwalbagewadi** [comment]
I to want to be a contributor any suggestions

**Comment by prajwalbagewadi** [comment]
Sir can send screen shots of sphinx doc

**Comment by prajwalbagewadi** [comment]
Sir is it this type of a diagram
![images (6)](https://user-images.githubusercontent.com/77821176/105578380-c7eb3680-5da5-11eb-88af-edb719942539.png)

**Comment by prajwalbagewadi** [comment]
I like to work on updating docs count me in

**Comment by bessman** [comment]
The docs in question can be found in https://github.com/fossasia/pslab-python/tree/development/docs, and in docstrings of individual classes and methods. The specific issue mentioned in the title was solved by https://github.com/fossasia/pslab-python/pull/141.

The documentation in https://github.com/fossasia/pslab-python/tree/development/docs is largely out of date. For now, we can remove it in favor of building the documentation entirely from docstrings. Additional documentation in the form of extended examples, working principles, and background theory could be added to https://github.com/fossasia/pslab-documentation.

**Comment by prajwalbagewadi** [comment]
Ok sir thanks you
