### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by bessman** [fossasia/pslab-python#116]
PSL lacks unit tests. I'm interested in writing them, if you think they would be useful to the project.

- [ ] Add unit tests for Peripherals
- [x] Add unit tests for achan
- [ ] Add units tests for analyticsClass
- [ ] Add unit tests for commands_proto
- [ ] Add unit tests for digital_channel
- [x] Add unit tests for packet_handler
- [ ] Add unit tests for sciencelab
- [ ] Add unit tests for sensorlist

Add unit tests for SENSORS
- [ ] AD7718_class
- [ ] AD9833
- [ ] ADS1115
- [ ] BH1750
- [ ] BMP180
- [ ] ComplementaryFilter
- [ ] HMC5883L
- [ ] Kalman
- [ ] MF522
- [ ] MLX90614
- [ ] MPU6050
- [ ] MPU925x
- [ ] SHT21
- [ ] SSD1306
- [ ] Sx1276
- [ ] TSL2561
- [ ] supported

**Comment by mariobehling** [comment]
This would be great. We would also like to invite you to our weekly meeting at 5 pm CET on Saturdays to discuss details and find out how we could involve you more. Please join the call here https://meet.jit.si/fossasia-hw

**Comment by bessman** [comment]
Thanks for the invite! I might not be able to join tomorrow though. If not, I'll join next week.

**Comment by BHAKTA-VARUN** [comment]
hi everyone,
can i work with you guys
I am a beginner here.
you can assign me any task

**Comment by bessman** [comment]
Hi @BHAKTA-VARUN, tests are being added as part of the ongoing refactorization effort: #127. Unfortunately it is not really beginner friendly.

Do you have a PSLab device?

**Comment by BHAKTA-VARUN** [comment]
no sir i don't have  PSLab device

but thank you very much for showing concern. If in any way i can help you
please let me know.
I learnt python and mysql. If you require those skills please let me know.

Finally, please suggest any thing which I can learn to be able to
contribute.

thank you

**Comment by bessman** [comment]
Closing this since most built-in instruments now have tests.

**Comment by viric** [comment]
Is it possible that tests for 'external' fail today? It seems there is outdated code. How do you run the tests currently?

**Comment by bessman** [comment]
Tests are run with `tox -e playback` (using recorded serial traffic, requires no hardware) or `tox -e integration` (requires hardware). There are only a few tests for external right now, because as you noticed most of that code is outdated. The tests that do exist are passing.
