### ISSUE TITLE
Merge repositories to be more user friendly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-python#13]
The readme.md already states "clone two repositories". Why we have two repositories then? Please merge the repos and import "apps" as a folder into this repo.

**Comment by wavicles** [comment]
@mariobehling  Two separate repositories are created because,  if users are only interested in using PSLab as an acquisition device without a display, the don't need to download the huge graphics dependencies such as pyqt4, pyqtgraph and screenshots etc.

**Comment by wavicles** [comment]
Some of the Debian package maintainers follow this method. But If required it is possible to merge  pslab-apps repo with pslab.

**Comment by mariobehling** [comment]
@wavicles People can still use PSLab as an acquisition device and the code stays separate. Please just add it here into a folder. Debian people can still follow their procedure as well.

**Comment by mariobehling** [comment]
@wavicles Actually this also depends on the question if there might be a chance to implement the whole thing as a web app that runs in the browser.

**Comment by wavicles** [comment]
Yes. This is possible.  I will start working on this idea.

**Comment by wavicles** [comment]
@mariobehling  For implementing the whole thing as a web app, some sort of server needs to be present for hosting the files, right?

**Comment by wavicles** [comment]
If we want PSLab to be used as stand alone tool, then the server and wifi needs to run on PSLab itself. In which case, an ESP8266 module can be added to PSLab board and server code must be uploaded on to it.

**Comment by mariobehling** [comment]
Well, ok, it is possible to build a device, but then the goal is not anymore to run it on any PC. So, this would mean PSLabs comes on a Raspi or similar with a wifi chip. Then it cannot be simply installed on a PC. So, what really needs to be defined is the use case and ask ourselves: What do people have available to get them started? PC, mico-computers like Raspis, mobile phone? Who do you want to enable? If you want to have the broadest possible outreach, it should probably be a phone app and it could be a web app running on the phone as well. We could have all kinds of syncs with Firebase or other technologies. So, what is your ultimate goal?
