### ISSUE TITLE
Update pin names

### ISSUE THREAD

**Issue by bessman** [fossasia/pslab-python#140]
Change all instances of

- ID1/2/3/4 -> LA1/2/3/4
- SEN -> RES
- AN8 -> VOL
- CNTR -> FRQ
- W1/2 -> SI1/2

**Comment by MLJBrackett** [comment]
Hey @bessman I would like to do this, could you assign it to me?

**Comment by Nanak360** [comment]
I would like to work on it. It will be very helpful if I could get a little more information. 
![Screenshot (275)](https://user-images.githubusercontent.com/36790357/95310992-ade72000-08aa-11eb-8114-732507f12d0e.png)
![Screenshot (276)](https://user-images.githubusercontent.com/36790357/95310996-ae7fb680-08aa-11eb-8fca-887a6ec84e66.png)

I see many instances of ID1, ID2, SEN
Should I change them all in each and every file?

**Comment by bessman** [comment]
Thanks! Yes, that's right. Every instance in every file.

**Comment by Nanak360** [comment]
All right, I'll work on it. Would you please assign me?
I would also like to know if this contribution will be a part of Hacktoberfest.

**Comment by bessman** [comment]
Sure, we can opt in and tag your pull request as hacktoberfest-approved.

**Comment by Nanak360** [comment]
@bessman I have changed each and every instance from all the files and created a pull request. Please guide me through, what do I do now for the Hacktoberfest part.

**Comment by bessman** [comment]
Fixed by #141.
