### ISSUE TITLE
explain installing pslab-python to the system and setting PYTHONPATH

### ISSUE THREAD

**Issue by orangecms** [fossasia/pslab-python#142]
see also https://github.com/fossasia/pslab-documentation/pull/119#issuecomment-705048446

For PSLab desktop app users, especially on Windows, connecting pslab-desktop to pslab-python needs some more information.

**Comment by bessman** [comment]
I wonder if we could simplify the windows instructions. Theoretically, the Linux instructions should actually be platform independent.

We should test if
```pip install git+https://github.com/fossasia/pslab-python@master
```
works on Windows and Mac. If it does, we could cut most of the current installation instructions entirely.

**Comment by bessman** [comment]
As pslab-python is now on [pypi](https://pypi.org/project/pslab/), installing should now be as simple as `pip install pslab`, regardless of operating system.
