### ISSUE TITLE
Bug: CH1 and CH2 autorange set incorrectly

### ISSUE THREAD

**Issue by cynthi8** [fossasia/pslab-python#159]
1. Reading a measurement from CH1 or CH2
2. Removing the measurement probes
3. Re-inserting them 

yields incorrect results.

When `_voltmeter_autorange`is bypassed by calling `_measure_voltage` directly, this issue does not occur.

**Setup**
I connected CH1 measurement pins to I2C VDD (3.3 V) and GND and ran this code
```
import time
import sys
from PSL import sciencelab
I = sciencelab.connect()

channel = sys.argv[1]

while True:
    voltage = I.multimeter.measure_voltage(channel)
    print(channel, "=", voltage)
    time.sleep(1)
```
**Results**
![PSL_CH1_wrong_voltage](https://user-images.githubusercontent.com/71356003/105573540-4e633200-5d2c-11eb-8c2d-eb51d7984a71.png)

With `_measure_voltage` instead of `measure_voltage`,
![PSL_CH1_auto_range_bypassed](https://user-images.githubusercontent.com/71356003/105573560-70f54b00-5d2c-11eb-97be-c7e4cb5ded62.png)

**Comment by bessman** [comment]
Fixed in cc9ad37.

**Comment by cynthi8** [comment]
Ah ok, sorry, I didn't check. Thanks!

**Comment by bessman** [comment]
No worries. Good job on finding the bug either way. I'll draft a new release and push it to pypi shortly.
