### ISSUE TITLE
Migrate from Travis CI

### ISSUE THREAD

**Issue by orangecms** [fossasia/pslab-python#183]
We need to take care of migrating, it says

> Please be aware travis-ci.org will be shutting down by end of May 2021. Please consider migrating to travis-ci.com.

That is a week left only :scream: 

see e.g. https://travis-ci.org/github/fossasia/pslab-python/builds/772004871

**Comment by orangecms** [comment]
Update: They have extended the deadline to June 15.

**Comment by CloudyPadmal** [comment]
Let's migrate to GitHub actions 🙌🏼

**Comment by bessman** [comment]
That didn't work as well as I had hoped. It seems Github Actions are disabled for this repository. I don't have sufficient permissions to enable them.

**Comment by orangecms** [comment]
Yes, configuration is necessary first. Otherwise people could do all sorts of fun stuff just by opening PRs. @mariobehling could you provide that and/or grant the access rights? :)

**Comment by CloudyPadmal** [comment]
Looks like me neither.. @mariobehling can you please check?
