### ISSUE TITLE
Oscillosope data samples amount

### ISSUE THREAD

**Issue by cloudishBenne** [fossasia/pslab-python#210]
I don't know if it is my lack of understanding the usage of the oscilloscope module or if i found a bug. But whatever timedelta i use, i cannot get above 229 samples per measurement. Could somebody help me there?
I have the v5 hardware.

**Comment by bessman** [comment]
Could you show a piece of code that reproduces your issue? It's difficult to say what the problem might be without seeing what you are trying to do.

**Comment by bessman** [comment]
Closing due to lack of feedback.
