### ISSUE TITLE
Add Open Firmware and Hardware Schematics

### ISSUE THREAD

**Issue by wavicles** [fossasia/pslab-python#37]
#https://github.com/fossasia/labs.fossasia.org/issues/205

For the PSLab project we need a completely Open firmware and hardware schematics. There are already schematics in pdf format. In order to progress to the next level of development these files need to be implemented in code and added to the repository.

Please create a list of features for the firmware and sample implementations for tests. Add your schematics to the PSLab repo and create a fully functional hardware, that can be freely used by others.

PSLab is a new addition to FOSSASIA Science Lab. This tiny pocket lab provides an array of necessary equipments for doing science and engineering experiments. It can function like an oscilloscope, waveform generator, frequency counter, programmable voltage and current source and also as a data logger. The control and measurement functions are written in Python programming language. Pyqtgraph is used for plotting library. A variety of experiments can be performed using GUI applications written in python. PSLab is interfaced and powered by USB port of the computer.

Repository: https://github.com/fossasia/pslab

Website: http://pslab.fossasia.org

**Comment by mariobehling** [comment]
We have dedicated repositories for this now. Closing it.
