### ISSUE TITLE
Add Calibration Utility 

### ISSUE THREAD

**Issue by jithinbp** [fossasia/pslab-python#45]
The PSLab unit's analog and digital features must be calibrated in order to make it accurate.
The [ADS1115 16-bit ADC](http://www.ti.com/lit/ds/symlink/ads1113.pdf) is a 4-channel, 0-3.3V ADC that can be interfaced via I2C . Typical initial accuracy of the internal voltage reference 0.01% and  data rates higher than 500SPS are possible. It is cost effective, and convenient breakout boards that can directly plug into the PSLab's I2C port are available. Buy links: [A](https://www.aliexpress.com/store/product/16-Bit-I2C-ADS1115-Module-ADC-4-channel-with-Pro-Gain-Amplifier-for-Arduino-RPi/612195_32392824449.html) , [B](https://www.adafruit.com/product/1085) , [C](https://www.aliexpress.com/item/16-Bit-I2C-4-Channel-ADS1115-Module-ADC-with-Pro-Gain-Amplifier-For-Arduino-New/32639491517.html)
Therefore, it appears to be most suited to calibrate individual PSLab devices.

Tasks
- Add I2C communication library for ADS1115
  - Include methods for reading single ended , and differential channels
  - Include selection of voltage range and voltage reference
- Add Qt based UI . Features :  These changes will be made in pslab-desktop-apps: [issue #100](https://github.com/fossasia/pslab-desktop-apps/issues/100)
  - Calibrate CH1, CH2, CH3 & PV1, PV2, PV3 using ADS1115. Generate Cubic interpolation functions for each
  - Calibrate PCS using a measured Load resistor, and calibrated analog channel. Generate interpolation function
  - Calibrate CAP using precision capacitors
  - Write all calibration constants into flash memory after assigning a timestamp
  - Store raw calibration data in a client-side folder

**Comment by souravsingh** [comment]
@jithinbp Is the issue fixed? I would like to help fix the issue.

**Comment by sabirma** [comment]
I'm working on this one. Got half of it covered already. 
We'll find something else for you

**Comment by jithinbp** [comment]
I'm working on this one. Got half of it covered already.
We'll find something else for you
