### ISSUE TITLE
accessing invalid reference in sciencelab.py

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-python#48]
accessing CP.SET_ONBOARD_RGB from commands_proto.py [here](https://github.com/fossasia/pslab-python/blob/development/PSL/sciencelab.py#L3713) and there on no reference of SET_ONBOARD_RGB on commands_proto.py [here](https://github.com/fossasia/pslab-python/blob/development/PSL/commands_proto.py)

**Comment by jithinbp** [comment]
There are bound to be many such relics . I was eliminating features that
didn't work/were required. So some constants must be leftover.
It'll have to be compared with what's in the firmware, but we can do that
later
