### ISSUE TITLE
error in loop range in I2C capture function

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab-python#60]
https://github.com/fossasia/pslab-python/blob/development/PSL/Peripherals.py#L608
Loop range should be (total_chans * channel_length)/2

**Comment by jithinbp** [comment]
That function has been replaced by three different functions now(all three
tested with mpu6050 sensor).
 I'll rewrite `capture` in terms of those three .
Thanks

**Comment by jithinbp** [comment]
merged via #67
