### ISSUE TITLE
sciencelab.capture_multiple does not return correct data

### ISSUE THREAD

**Issue by jithinbp** [fossasia/pslab-python#72]
https://github.com/fossasia/pslab-python/blob/development/PSL/sciencelab.py#L593

This function is meant to be used as an oscilloscope where > 4 channels need to be recorded. Up to 4 channels can be simultaneously sampled using capture_traces instead.

The function accepts channel names as extra arguments, and the firmware scans through a sorted list of specified channels . The retrieved buffer must then be parsed into separate Y axes data , and the time axes for each channel must also be returned separately since this is sequential not simultaneous sampling.

**Comment by bessman** [comment]
This should have been closed as of a5b955d.
