### ISSUE TITLE
x.setOffset() is missing

### ISSUE THREAD

**Issue by gabru-md** [fossasia/pslab-python#73]
In the file : `achan.py` on `line 128` it says
```python
x.setOffset(1.65)
```
but in the `class analogInputSource` there is no such function. Is it missing by mistake or by purpose?
Can someone clarify? If it is needed to set values of `self.defaultOffsetcode` then I can do the same.
ping @jithinbp @CloudyPadmal

**Comment by bhadreshpsavani** [comment]
i think this will not create any problem because in [achan.py](https://github.com/fossasia/pslab-python/blob/development/PSL/achan.py), `line 128`  in `x.setOffset(1.65)`  is commented

@CloudyPadmal shall we close this issue or make some changes?

**Comment by bessman** [comment]
Closing this since the recent achan refactorization removed this line.
