### ISSUE TITLE
Update the sensorlist file

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/pslab-python#93]
[sensorlist.py](https://github.com/fossasia/pslab-python/blob/development/PSL/sensorlist.py) file is a bit outdated and there are lot of new sensors in the market. [Adafruit I2C List](https://learn.adafruit.com/i2c-addresses/the-list) is fairly updated and trustworthy to take as a reference.

We need to update the [sensorlist.py](https://github.com/fossasia/pslab-python/blob/development/PSL/sensorlist.py) with the new I2C addresses and validate the old addresses. If there's any change, make it..

**Comment by bhadreshpsavani** [comment]
I am working on this issue
